FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Installation de FastAPI, PostgreSQL et du runtime Machine Learning
RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    psycopg2-binary \
    pandas \
    joblib \
    scikit-learn \
    xgboost\
    shap

COPY . .

EXPOSE 8000

CMD ["uvicorn", "03_api:app", "--host", "0.0.0.0", "--port", "8000"]